spring:
  data:
    mongodb:
      uri: mongodb://localhost/customer-api
server:
  port: 8081
  error:
    whitelabel:
      enabled: false
feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
        loggerLevel: basic
apis:
  address-api:
    url: http://localhost:8082
