spring:
  data:
    mongodb:
      uri: mongodb://localhost/address-api
server:
  port: 8082
  error:
    whitelabel:
      enabled: false
feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
        loggerLevel: basic
apis:
  customer-api:
    url: http://localhost:8081
